public class FatApexClass {
    public void main() {
        String message = 'Hello, world!';
    }

    public void GeneratedMethod1() {
        Integer methodInt = 1;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod2() {
        Integer methodInt = 2;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod3() {
        Integer methodInt = 3;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod4() {
        Integer methodInt = 4;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod5() {
        Integer methodInt = 5;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod6() {
        Integer methodInt = 6;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod7() {
        Integer methodInt = 7;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod8() {
        Integer methodInt = 8;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod9() {
        Integer methodInt = 9;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod10() {
        Integer methodInt = 10;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod11() {
        Integer methodInt = 11;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod12() {
        Integer methodInt = 12;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod13() {
        Integer methodInt = 13;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod14() {
        Integer methodInt = 14;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod15() {
        Integer methodInt = 15;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod16() {
        Integer methodInt = 16;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod17() {
        Integer methodInt = 17;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod18() {
        Integer methodInt = 18;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod19() {
        Integer methodInt = 19;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod20() {
        Integer methodInt = 20;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod21() {
        Integer methodInt = 21;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod22() {
        Integer methodInt = 22;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod23() {
        Integer methodInt = 23;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod24() {
        Integer methodInt = 24;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod25() {
        Integer methodInt = 25;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod26() {
        Integer methodInt = 26;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod27() {
        Integer methodInt = 27;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod28() {
        Integer methodInt = 28;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod29() {
        Integer methodInt = 29;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod30() {
        Integer methodInt = 30;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod31() {
        Integer methodInt = 31;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod32() {
        Integer methodInt = 32;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod33() {
        Integer methodInt = 33;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod34() {
        Integer methodInt = 34;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod35() {
        Integer methodInt = 35;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod36() {
        Integer methodInt = 36;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod37() {
        Integer methodInt = 37;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod38() {
        Integer methodInt = 38;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod39() {
        Integer methodInt = 39;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod40() {
        Integer methodInt = 40;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod41() {
        Integer methodInt = 41;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod42() {
        Integer methodInt = 42;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod43() {
        Integer methodInt = 43;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod44() {
        Integer methodInt = 44;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod45() {
        Integer methodInt = 45;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod46() {
        Integer methodInt = 46;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod47() {
        Integer methodInt = 47;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod48() {
        Integer methodInt = 48;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod49() {
        Integer methodInt = 49;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod50() {
        Integer methodInt = 50;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod51() {
        Integer methodInt = 51;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod52() {
        Integer methodInt = 52;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod53() {
        Integer methodInt = 53;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod54() {
        Integer methodInt = 54;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod55() {
        Integer methodInt = 55;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod56() {
        Integer methodInt = 56;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod57() {
        Integer methodInt = 57;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod58() {
        Integer methodInt = 58;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod59() {
        Integer methodInt = 59;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod60() {
        Integer methodInt = 60;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod61() {
        Integer methodInt = 61;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod62() {
        Integer methodInt = 62;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod63() {
        Integer methodInt = 63;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod64() {
        Integer methodInt = 64;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod65() {
        Integer methodInt = 65;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod66() {
        Integer methodInt = 66;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod67() {
        Integer methodInt = 67;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod68() {
        Integer methodInt = 68;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod69() {
        Integer methodInt = 69;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod70() {
        Integer methodInt = 70;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod71() {
        Integer methodInt = 71;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod72() {
        Integer methodInt = 72;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod73() {
        Integer methodInt = 73;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod74() {
        Integer methodInt = 74;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod75() {
        Integer methodInt = 75;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod76() {
        Integer methodInt = 76;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod77() {
        Integer methodInt = 77;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod78() {
        Integer methodInt = 78;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod79() {
        Integer methodInt = 79;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod80() {
        Integer methodInt = 80;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod81() {
        Integer methodInt = 81;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod82() {
        Integer methodInt = 82;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod83() {
        Integer methodInt = 83;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod84() {
        Integer methodInt = 84;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod85() {
        Integer methodInt = 85;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod86() {
        Integer methodInt = 86;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod87() {
        Integer methodInt = 87;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod88() {
        Integer methodInt = 88;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod89() {
        Integer methodInt = 89;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod90() {
        Integer methodInt = 90;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod91() {
        Integer methodInt = 91;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod92() {
        Integer methodInt = 92;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod93() {
        Integer methodInt = 93;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod94() {
        Integer methodInt = 94;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod95() {
        Integer methodInt = 95;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod96() {
        Integer methodInt = 96;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod97() {
        Integer methodInt = 97;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod98() {
        Integer methodInt = 98;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod99() {
        Integer methodInt = 99;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod100() {
        Integer methodInt = 100;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void BottomAnchorMethod() {
        String message = 'I\'m just here to create diff regions above me';
    }
}